PROJECT_NAME := Tamagotchi_unit_tests
EXTRA_COMPONENT_DIRS := $(realpath ../components/esp ../components/generic ../components/app $ENV{IDF_PATH}/tools/unit-test-app/components)
TEST_COMPONENTS ?= RecyclingContainer EspGL SPIFFSDriver BitmapLoader PetGenerator Pet Gomoku
include $(IDF_PATH)/make/project.mk