PROJECT_NAME := Tamagotchi_unit_tests
EXTRA_COMPONENT_DIRS := $(realpath ../components/esp ../components/generic $ENV{IDF_PATH}/tools/unit-test-app/components)
TEST_COMPONENTS ?= ST7789Driver RecyclingContainer
include $(IDF_PATH)/make/project.mk